// ignore_for_file: file_names

List<Map<String, dynamic>> universiteFilieres = [
  {'id_universite': 1, 'id_filiere': 1},
  {'id_universite': 1, 'id_filiere': 2},
  {'id_universite': 1, 'id_filiere': 3},
  {'id_universite': 1, 'id_filiere': 4},
  {'id_universite': 1, 'id_filiere': 5},
  {'id_universite': 1, 'id_filiere': 6},
  {'id_universite': 1, 'id_filiere': 7},
  {'id_universite': 1, 'id_filiere': 8},
  {'id_universite': 1, 'id_filiere': 9},
  {'id_universite': 1, 'id_filiere': 10},
  {'id_universite': 1, 'id_filiere': 11},
  {'id_universite': 1, 'id_filiere': 12},
  {'id_universite': 1, 'id_filiere': 13},
  {'id_universite': 1, 'id_filiere': 14},
  {'id_universite': 1, 'id_filiere': 15},
  {'id_universite': 1, 'id_filiere': 16},
  {'id_universite': 1, 'id_filiere': 17},
  {'id_universite': 1, 'id_filiere': 18},
  {'id_universite': 1, 'id_filiere': 19},
  {'id_universite': 1, 'id_filiere': 20},
  {'id_universite': 1, 'id_filiere': 21},
  {'id_universite': 1, 'id_filiere': 22},
  {'id_universite': 1, 'id_filiere': 23},
  {'id_universite': 1, 'id_filiere': 24},
  {'id_universite': 1, 'id_filiere': 25},
  {'id_universite': 1, 'id_filiere': 26},
];
