// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnRjz-jqXWIoKHXaPKUieWhhgUB-W5UYQ',
    appId: '1:227340173362:web:414857c46e1f25e9cd3c2b',
    messagingSenderId: '227340173362',
    projectId: 'application-8ef5a',
    authDomain: 'application-8ef5a.firebaseapp.com',
    storageBucket: 'application-8ef5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbw647zSsa533BwdPQ4kbiJVy77eoa5fQ',
    appId: '1:227340173362:android:7a74927830200baecd3c2b',
    messagingSenderId: '227340173362',
    projectId: 'application-8ef5a',
    storageBucket: 'application-8ef5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbovgN3Ymy0EJHuwe4-arGLfiweLVnVWU',
    appId: '1:227340173362:ios:1353328b5b8c8d64cd3c2b',
    messagingSenderId: '227340173362',
    projectId: 'application-8ef5a',
    storageBucket: 'application-8ef5a.appspot.com',
    iosBundleId: 'com.example.application',
  );
}
